Name: Shreyas Dongre   
Roll no: 082          
Stream: CS (AI)      
Division: I                         
Semester: 5th Semester                                           
Batch: I-3            
                                                                       Date: 28/7/2022       
Subject: DL
###Experiment-2

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
#performing one hot encoding on tangent var

#converting categorical to dummy rep num
df1=pd.get_dummies(df['Species'])

In [ ]:
df1.head()

Iris-setosa  Iris-versicolor  Iris-virginica
0            1                0               0
1            1                0               0
2            1                0               0
3            1                0               0
4            1                0               0

In [ ]:
#dropping unused cols
#if flase ret copy, def=false
#otherwise do op inplace and return none
df.drop('Species',axis=1,inplace=True)
df.drop('Id',axis=1,inplace=True)

In [ ]:
#concatenanting one hot encoding with init dataset to form final dataset
final_df=pd.concat([df,df1],axis=1)
final_df.head() 

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
0            5.1           3.5            1.4           0.2            1   
1            4.9           3.0            1.4           0.2            1   
2            4.7           3.2            1.3           0.2            1   
3            4.6           3.1            1.5           0.2            1   
4            5.0           3.6            1.4           0.2            1   

   Iris-versicolor  Iris-virginica  
0                0               0  
1                0               0  
2                0               0  
3                0               0  
4                0               0

In [ ]:
#Standardizing the 4 num cols
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
std_scalar = StandardScaler()
#makes data scale free by conv statistical dist of data
#mean is made 0 and var is made 1
#x=(x-mean)/std
final_df.iloc[:,[0,1,2,3]] = std_scalar.fit_transform(final_df.iloc[:,[0,1,2,3]])
final_df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
0      -0.900681      1.032057      -1.341272     -1.312977            1   
1      -1.143017     -0.124958      -1.341272     -1.312977            1   
2      -1.385353      0.337848      -1.398138     -1.312977            1   
3      -1.506521      0.106445      -1.284407     -1.312977            1   
4      -1.021849      1.263460      -1.341272     -1.312977            1   

   Iris-versicolor  Iris-virginica  
0                0               0  
1                0               0  
2                0               0  
3                0               0  
4                0               0

In [ ]:
#building 3 layer feed fwd network

#init weights and biases first
np.random.seed(42)
w_i_h1=np.random.rand(4,1)
w_i_h2=np.random.rand(4,1)
w_h_o1=np.random.rand(2,1)
w_h_o2=np.random.rand(2,1)
w_h_o3=np.random.rand(2,1)

bias1=np.random.rand(1)
bias2=np.random.rand(1)

In [ ]:
w_i_h2

array([[0.15601864],
       [0.15599452],
       [0.05808361],
       [0.86617615]])

In [ ]:
w_h_o3

array([[0.83244264],
       [0.21233911]])

In [ ]:
bias1

array([0.18182497])

In [ ]:
#func of sigmoid
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
input=final_df.iloc[:,0:4]
input

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.900681      1.032057      -1.341272     -1.312977
1        -1.143017     -0.124958      -1.341272     -1.312977
2        -1.385353      0.337848      -1.398138     -1.312977
3        -1.506521      0.106445      -1.284407     -1.312977
4        -1.021849      1.263460      -1.341272     -1.312977
..             ...           ...            ...           ...
145       1.038005     -0.124958       0.819624      1.447956
146       0.553333     -1.281972       0.705893      0.922064
147       0.795669     -0.124958       0.819624      1.053537
148       0.432165      0.800654       0.933356      1.447956
149       0.068662     -0.124958       0.762759      0.790591

[150 rows x 4 columns]

In [ ]:
#feedfwd step 1:- input to hidden layer
Z2_1=np.dot(input,w_i_h1)+bias1
Z2_2=np.dot(input,w_i_h2)+bias2

In [ ]:
#feedfwd step2
h2_1=sigmoid(Z2_1)
h2_2=sigmoid(Z2_2)

In [ ]:
#each o/p neuron gets ip from both hidden neuron so ppending them
h2=np.append(h2_1,h2_2,axis=1)

In [ ]:
h2.shape

(150, 2)

In [ ]:
O2_1 = np.dot(h2,w_h_o1)
O2_2 = np.dot(h2,w_h_o2)
O2_3 = np.dot(h2,w_h_o3)

In [ ]:
#generating op
o1=sigmoid(O2_1)
o2=sigmoid(O2_2)
o3=sigmoid(O2_3)

In [ ]:
o1.shape #we have 150 samples

(150, 1)

In [ ]:
o1[2]

array([0.56156672])

In [ ]:
o2[2]

array([0.55666158])

In [ ]:
o3[2]

array([0.54109451])

In [ ]:
 #calc error
 f1 = np.array(final_df.iloc[:,4])
 f1=f1.reshape((-1,1))
 e1=f1-o1

In [ ]:
#e1
f2 = np.array(final_df.iloc[:,5])
f2=f2.reshape((-1,1))
e2=f2-o2

In [ ]:
f3 = np.array(final_df.iloc[:,5])
f3=f3.reshape((-1,1))
e3=f3-o3

In [ ]:
error=np.multiply(e1,e1)+np.multiply(e2,e2)+np.multiply(e3,e3)

In [ ]:
error_total=np.sum(error)

In [ ]:
error_total

151.74137427802202

In [ ]:

#changing init weights and biases (increasing seed value) 
np.random.seed(89)
w_i_h1=np.random.rand(4,1)
w_i_h2=np.random.rand(4,1)
w_h_o1=np.random.rand(2,1)
w_h_o2=np.random.rand(2,1)
w_h_o3=np.random.rand(2,1)

bias1=np.random.rand(1)
bias2=np.random.rand(1)

input=final_df.iloc[:,0:4]
Z2_1=np.dot(input,w_i_h1)+bias1
Z2_2=np.dot(input,w_i_h2)+bias2


h2_1=sigmoid(Z2_1)
h2_2=sigmoid(Z2_2)

#each o/p neuron gets ip from both hidden neuron so ppending them
h2=np.append(h2_1,h2_2,axis=1)

O2_1 = np.dot(h2,w_h_o1)
O2_2 = np.dot(h2,w_h_o2)
O2_3 = np.dot(h2,w_h_o3)

#generating op
o1=sigmoid(O2_1)
o2=sigmoid(O2_2)
o3=sigmoid(O2_3)

 #calc error
f1 = np.array(final_df.iloc[:,4])
f1=f1.reshape((-1,1))
e1=f1-o1

#e1
f2 = np.array(final_df.iloc[:,5])
f2=f2.reshape((-1,1))
e2=f2-o2

f3 = np.array(final_df.iloc[:,5])
f3=f3.reshape((-1,1))
e3=f3-o3

error=np.multiply(e1,e1)+np.multiply(e2,e2)+np.multiply(e3,e3)
error_total_II=np.sum(error)
print(error_total_II) 

139.30013670337803


In [ ]:
#changing init weights and biases (decreasing seed value) 
np.random.seed(20)
w_i_h1=np.random.rand(4,1)
w_i_h2=np.random.rand(4,1)
w_h_o1=np.random.rand(2,1)
w_h_o2=np.random.rand(2,1)
w_h_o3=np.random.rand(2,1)

bias1=np.random.rand(1)
bias2=np.random.rand(1)

input=final_df.iloc[:,0:4]
Z2_1=np.dot(input,w_i_h1)+bias1
Z2_2=np.dot(input,w_i_h2)+bias2


h2_1=sigmoid(Z2_1)
h2_2=sigmoid(Z2_2)

#each o/p neuron gets ip from both hidden neuron so ppending them
h2=np.append(h2_1,h2_2,axis=1)

O2_1 = np.dot(h2,w_h_o1)
O2_2 = np.dot(h2,w_h_o2)
O2_3 = np.dot(h2,w_h_o3)

#generating op
o1=sigmoid(O2_1)
o2=sigmoid(O2_2)
o3=sigmoid(O2_3)

 #calc error
f1 = np.array(final_df.iloc[:,4])
f1=f1.reshape((-1,1))
e1=f1-o1

#e1
f2 = np.array(final_df.iloc[:,5])
f2=f2.reshape((-1,1))
e2=f2-o2

f3 = np.array(final_df.iloc[:,5])
f3=f3.reshape((-1,1))
e3=f3-o3

error=np.multiply(e1,e1)+np.multiply(e2,e2)+np.multiply(e3,e3)
error_total_II=np.sum(error)
print(error_total_II) 

154.48385610348697


In [ ]:
#add one more neuron in the hidden layer(2->3)
#initialize weights and biases first
np.random.seed(42)
w_i_h1=np.random.rand(4,1)
w_i_h2=np.random.rand(4,1)
w_i_h3=np.random.rand(4,1)
w_h_o1=np.random.rand(3,1)
w_h_o2=np.random.rand(3,1)
w_h_o3=np.random.rand(3,1)
bias1=np.random.rand(1)
bias2=np.random.rand(1)
bias3=np.random.rand(1)
input=final_df.iloc[:,0:4]
input
#Feedforward Step1- input to hidden layer
z2_1=np.dot(input,w_i_h1)+bias1
z2_2=np.dot(input,w_i_h2)+bias2
z2_3=np.dot(input,w_i_h3)+bias3
#Feedforward Step2
h2_1=sigmoid(z2_1)
h2_2=sigmoid(z2_2)
h2_3=sigmoid(z2_3)
#each output neuron gets input from both hidden layers so append both into an array
h2=np.append(h2_1,h2_2,axis=1)
h2=np.append(h2,h2_3,axis=1)
#Feedforward Step3 - input from hidden layer to output
o2_1=np.dot(h2,w_h_o1)
o2_2=np.dot(h2,w_h_o2)
o2_3=np.dot(h2,w_h_o3)
#generating outputs
o1=sigmoid(o2_1)
o2=sigmoid(o2_2)
o3=sigmoid(o2_3)
o1.shape
#Error calculation
f1=np.array(final_df.iloc[:,4])
f1=f1.reshape(-1,1)
e1=f1-o1
#Error calculation
f2=np.array(final_df.iloc[:,5])
f2=f2.reshape(-1,1)
e2=f2-o2
#Error calculation
f3=np.array(final_df.iloc[:,6])
f3=f3.reshape(-1,1)
e3=f3-o3
error=np.multiply(e1,e1)+np.multiply(e2,e2)+np.multiply(e3,e3)
error_total=np.sum(error)
error_total

147.44942573200146

In [ ]:
#! jupyter nbconvert --to html I082_Shreyas_Dongre_DL_Exp2.ipynb

#Conclusion:
1) A feed forward ANN with 3 layers was implemented which has 4 neurons are present in input layer, 2 neurons in hidden layer and 3 neurons in output layer.                         
2)We also changed seed values and then the number of neurons in the hidden layer to see the variation in error. 
We saw that increase and decrease in seed value both decreased the error while addition of neuron in the hidden layer increased the error.